# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1-W9iuct4TWnBAwlgQFAJJ_A-tzTv-A
"""

import matplotlib.pyplot as plt

data = []
for i in range(1, 8):
    a = int(input("Enter any number: "))
    data.append(a)

plt.hist(data)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

n, bins, patches = plt.hist(data, bins=5, edgecolor='black')

colors = ['purple', 'green', 'blue', 'orange', 'red']

for patch, color in zip(patches, colors):
    patch.set_facecolor(color)

plt.xlabel('Values')
plt.ylabel('Frequency')
plt.title('Histogram with Colors')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
X = [0,1,2,3,4,5]
Y = [0,10,20,20,10,0]
n = len(X)
mean_X = np.mean(X)
mean_Y = np.mean(Y)
num = 0
den = 0
for k in range(n):
    num = num+((X[k]-mean_X)*(Y[k]-mean_Y))
    den = den + ((X[k]-mean_X)**2)
m = num/den
c = mean_Y - (m*mean_X)
plt.scatter(X,Y, color = 'red')
plt.plot(X,Y,color='blue')
plt.show()